version: '3.8'

services:
  frontend:
    image: DOCKER_USERNAME/frontend:latest
    ports:
      - "3000:3000"
    env_file:
      - ./frontend/.env
    depends_on:
      - primary-backend

  primary-backend:
    image: DOCKER_USERNAME/primary-backend:latest
    ports:
      - "4000:4000"
      - "8080:8080"
    env_file:
      - ./backend/primary-backend/.env
    depends_on:
      - redis
      - redis-queue

  worker:
    image: DOCKER_USERNAME/worker:latest
    env_file:
      - ./backend/worker/.env
    depends_on:
      - redis
      - redis-queue

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  redis-queue:
    image: redis:alpine
    ports:
      - "6380:6379"
